version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: choises-backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
      PORT: 8081
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge